---
- name: SQL Server Configuration Validation Check
  hosts: all
  gather_facts: yes
  vars:
    configuration_report: []
  tasks:
    - name: Include role - sql server configuration validation
      ansible.builtin.include_role:
        name: ./SQL_Server/ansible_role_validate_sql_server_configuration