---
- name: Playbook to access CIFS share path
  hosts: all
  vars:
    cifs_server: SERVERHOST-01
    cifs_share: cluster_virtual_fileshare
    cifs_user: vsrivastava
    cifs_password: Admin@123
    drive_letter: "Z:"
  tasks:
    - name: Map network drive to CIFS share
      win_command: >
        net use {{ drive_letter }} "\\{{ cifs_server }}\{{ cifs_share }}"
        /user:{{ cifs_user }} "{{ cifs_password }}"
      register: map_drive_result

    - name: Show result of mapping
      debug:
        var: map_drive_result.stdout

    - name: List contents of the mapped drive
      win_shell: "dir {{ drive_letter }}\\"
      register: dir_result

    - name: Show directory contents
      debug:
        var: dir_result.stdout_lines
