---
- name: Install ClamAV application on RHEL
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Register EPEL on RHEL 9
      ansible.builtin.dnf:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm'
        state: present
      register: epel_status

    - name: Display output
      ansible.builtin.debug:
        var: epel_status
