---
- name: Ping Test
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Show OS Family
      debug:
        var: ansible_os_family

    - name: Linux
      ansible.builtin.ping:
      when: ansible_os_family != "Windows"

    - name: Windows
      ansible.windows.win_ping:
      when: ansible_os_family == "Windows"
