---
- name: Get SQL instance name info
  ansible.windows.win_shell: |
    $SQL_Instance = Get-SqlInstance -ServerInstance "{{ SQL_Server_Name }}"
    
    $All_SQL_Database = Get-SqlDatabase -ServerInstance "{{ SQL_Server_Instance }}"
    #$SQL_Replication_Info = 
    foreach($db in $All_SQL_Database.Name)
    { 
      $db_replication_info += Invoke-Sqlcmd -TrustServerCertificate -Query "SELECT SERVERPROPERTY('IsReplicationInstalled') AS ReplicationInstalled;" -ServerInstance "{{ SQL_Server_Instance }}" -Database $_
    }
    
    $sql_max_text_repl_size_info = Invoke-Sqlcmd -TrustServerCertificate -Query "EXEC sp_configure 'max text repl size';" -ServerInstance "{{ SQL_Server_Instance }}"

    $IsFullTextInstalled = Invoke-Sqlcmd -TrustServerCertificate -Query "SELECT SERVERPROPERTY('IsFullTextInstalled') AS FullTextSearchInstalled;" -ServerInstance "{{ SQL_Server_Instance }}"
    if($IsFullTextInstalled.FullTextSearchInstalled -eq 0 ) { $IsFullTextInstalled_Info = "IsFullTextInstalled: $False" } else { $IsFullTextInstalled_Info = "IsFullTextInstalled: $True" }

    $Filestream_status = Invoke-Sqlcmd -TrustServerCertificate -Query "SELECT value_in_use FROM sys.configurations WHERE name = 'filestream access level';" -ServerInstance "{{ SQL_Server_Instance }}"
    if($Filestream_status.value_in_use -eq 0) { $Filestream_info = "Filestream_info: Disabled" }
    elseif($Filestream_status.value_in_use -eq 1) { $Filestream_info = "Filestream_info: T-SQL access only" }
    elseif($Filestream_status.value_in_use -eq 2) { $Filestream_info =  "Filestream_info: T-SQL and Win32 streaming access" }
    else { $Filestream_info =  "Filestream_info: Incorrect / Garbage value obtained" }

    $SQL_Instance
    $db_replication_info
    $IsFullTextInstalled_Info
    $Filestream_info