---
- name: Get SQL instance name info
  ansible.windows.win_shell: |
    Get-SqlInstance -ServerInstance "{{ SQL_Server_Name }}"
  register: sql_instance_info

- name: Update SQL instance details into report
  ansible.builtin.set_fact:
    configuration_report: "SQL Instance Info: \n\n {{ configuration_report | default([]) + [ sql_instance_info.stdout_lines ] }}"

- name: Get SQL replication feature status (for all databases)
  ansible.builtin.win_shell: |
    $All_SQL_Database = Get-SqlDatabase -ServerInstance "{{ SQL_Server_Instance }}"
    foreach($db in $All_SQL_Database.Name)
    {
      Invoke-Sqlcmd -Query "SELECT SERVERPROPERTY('IsReplicationInstalled') AS ReplicationInstalled;" -ServerInstance "{{ SQL_Server_Instance }}" -Database $db
    }
  register: sql_replication_info

- name: Update SQL server db replication details into report
  ansible.builtin.set_fact:
    configuration_report: "DB Replication Info: \n\n {{ configuration_report | default([]) + [ sql_replication_info.stdout_lines ] }}"

- name: Get SQL server max text repl size info
  ansible.windows.win_shell: |
    Invoke-Sqlcmd -TrustServerCertificate -Query "EXEC sp_configure 'max text repl size';" -ServerInstance "{{ SQL_Server_Instance }}"
  register: sql_max_text_repl_size_info

- name: Update SQL server max text repl size details into report
  ansible.builtin.set_fact:
    configuration_report: "Max Text Repl Size Info: \n\n {{ configuration_report | default([]) + [ sql_max_text_repl_size_info.stdout_lines ] }}"

- name: Show report
  ansible.builtin.debug:
    var: configuration_report
