---
- name: Get SQL instance name info
  ansible.windows.win_shell: |
    Import-Module sqlserver
    Get-SqlInstance -ServerInstance "{{ SQL_Server_Name }}"
  register: sql_instance_info

- name: Update SQL instance details into report
  ansible.builtin.set_fact:
    configuration_report: "{{ configuration_report | default([]) + [ sql_instance_info ] }}"

- name: Get SQL server replication feature info
  ansible.windows.win_shell:
    Invoke-Sqlcmd -TrustServerCertificate -Query "EXEC sp_configure 'max text repl size';" -ServerInstance "{{ SQL_Server_Instance }}"
  register: sql_replication_info

- name: Update SQL server replication details into report
  ansible.builtin.set_fact:
    configuration_report: "{{ configuration_report | default([]) + [ sql_replication_info ] }}"

- name: Show report
  ansible.builtin.debug:
    var: configuration_report
