---
- name: Get SQL instance name details
  ansible.windows.win_shell: |
    Import-Module sqlserver
    Get-SqlInstance -ServerInstance "{{ SQL_Server_Name }}"
  register: sql_instance_info

- name: Update report
  ansible.builtin.set_fact:
    configuration_report: "{{ configuration_report | default([]) + [ sql_instance_info ] }}"

- name: Check DB connection
  community.general.mssql_script:
    login_user: "{{ ansible_user }}"
    login_password: "{{ ansible_password }}"
    login_host: "{{ mssql_host }}"
    login_port: "{{ mssql_port }}"
    db: master
    script: "SELECT 1"

- name: Show report
  ansible.builtin.debug:
    var: configuration_report
