---
- name: Get SQL instance name details
  ansible.windows.win_shell: |
    Import-Module sqlserver
    #Get-SqlInstance -ServerInstance "{{ SQL_Server_Name }}"
  register: sql_instance_info

- name: Update report
  ansible.builtin.set_fact:
    configuration_report: "{{ configuration_report | default([]) + [ sql_instance_info ] }}"

- name: Show report
  ansible.builtin.debug:
    var: configuration_report