---

# Get SQL Server Build Validation
- name: SQL Server Build Validation
  ansible.windows.win_shell: |
    $SQL_Server_Build_Validation_Report = [System.Collections.ArrayList]@()
    $logFile = '{{ logfile }}'
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    
    # Function to log messages
    function Log-Message {
        param([string]$message)
        Add-Content -Path $logFile -Value "$timestamp - $message"
        Write-Host $message
    }

    # Create Log File
    if(not(Test-path $logFile))
    {
      New-Item $logFile -ItemType File -Force
    }

    # Step-1: Get SQL Server Name
    $Query = @"
    select @@servername as 'servername\instancename',
      serverproperty('servername') as 'servername',
      serverproperty('machinename') as 'windows_name',
      serverproperty('computernamephysicalnetbios') as 'netbios_name',
      name from sys.servers where server_id = 0"
    "@
    try
    {
      $SQL_Server_Name = Invoke-Sqlcmd -TrustServerCertificate -Query $Query
      Log-Message $SQL_Server_Name
    }
    catch
    {
      Log-Message "Error: $($_.Exception.Message)"
    }

    # Step-2: Get Auth Scheme - Service Principal Name


    # Step-3: Get EBS Voulmes (All GPT except primary disk 'c')


    # Step-4

