---

# Get SQL Server Build Validation
- name: SQL Server Build Validation
  ansible.windows.win_shell: |
    $SQL_Server_Build_Validation_Report = [System.Collections.ArrayList]@()
    $logFile = '{{ logfile }}'
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    
    # Function to log messages
    function Log-Message {
        param([string]$message)
        Add-Content -Path $logFile -Value "$timestamp - $message"
        Write-Host $message
    }

    # Create Log File
    if(not(Test-path $logFile))
    {
      New-Item $logFile -ItemType File -Force
    }

    # Step-1: Get SQL Server Name
    $Query = "Select @@servername as 'servername\instancename', serverproperty('servername') as 'servername', serverproperty('machinename') as 'windows_name', serverproperty('computernamephysicalnetbios') as 'netbios_name', name from sys.servers where server_id = 0";
    try
    {
      $SQL_Server_Name = Invoke-Sqlcmd -TrustServerCertificate -Query $Query
      Log-Message "`r`n SQL Server Name Info:`r`n$($SQL_Server_Name | out-string)"
    }
    catch
    {
      Log-Message "Error: $($_.Exception.Message)"
    }

    # Step-2: Get Auth Scheme - Service Principal Name
    try
    {
      $SQL_Get_Auth_Scheme = Invoke-Sqlcmd -TrustServerCertificate -Query "select auth_scheme from sys.dm_exec_connections where session_id = @@spid";
    }
    catch
    {
      Log-Message "Error: $($_.Exception.Message)"
    }

    # Step-3: Get EBS Voulmes (All GPT except primary disk 'c')


    # Step-4 Allocation Unit size shall be 64KB (except C & D which come with the AMI)
    try
    {
      $wmiQuery = "SELECT Name, Label, Blocksize FROM Win32_Volume WHERE FileSystem='NTFS'"
      $Allocation_Unit_Size = Get-WmiObject -Query $wmiQuery -ComputerName '.' | Sort-Object Name | Select-Object Name, Label, Blocksize
      Log-Message "`r`n Allocation Unit Size Info:`r`n$($Allocation_Unit_Size | out-string)"
    }
    catch
    {
      Log-Message "Error: $($_.Exception.Message)"
    }
