---
# tasks file for sql_server_configuration_best_practices
- name: SQL Server Configuration Best Practices
  ansible.windows.win_shell: |
    $logFile = '{{ logfile }}'
    if(!(Test-path $logFile))
    {
      New-Item $logFile -ItemType File -Force
    }

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    # Function to log messages
    function Log-Message {
        param([string]$message)
        Add-Content -Path $logFile -Value "$timestamp - $message"
        Write-Host $message
    }
