---
- name: Linux (Splunk service restart)
  ansible.builtin.command: '{{ linux_splunk_install_path }}/bin/splunk restart'
  become: '{{ set_become }}'
  register: linux_splunk_service_restart_info

- name: Show registered output
  ansible.builtin.debug:
    var: linux_splunk_service_restart_info

- name: Linux )Splunk Service Status)
  ansible.builtin.command: '{{ linux_splunk_install_path }}/bin/splunk status'
  become: '{{ set_become }}'
  register: linux_splunk_service_status_info

- name: Set success facts
  ansible.builtin.set_fact:
    fact_rc: 0
    fact_msg: 'Splunk service state is running'
  when:
    - "'splunkd is running' | regexsearch(linux_splunk_service_status_info.stdout)"
