---
- name: Transform survey data to complex data structure
  ansible.builtin.template:
      src: templates/transform.j2
      dest: /var/tmp/paf_payload.yml
  become: true

- name: Read file content
  ansible.builtin.file:
    path: '/var/tmp/paf_payload.yml'
    state: present
    register: paf_payload_content

# - name: Read file content
#   ansible.builtin.set_fact:
#     paf_trigger_payload: "{{ lookup('ansible.builtin.file', '/var/tmp/paf_payload.yml') }}"
#   become: true

- name: Show file content
  ansible.builtin.debug:
    var: paf_payload_content
