---
- name: Transform survey data to complex data structure
  ansible.builtin.template:
      src: templates/transform.j2
      dest: /var/tmp/paf_payload.yml
  become: true

- name: Read file content
  ansible.builtin.command: cat '/var/tmp/paf_payload.yml'
  register: paf_trigger_payload

- name: Show file content
  ansible.builtin.debug:
    var: paf_trigger_payload | to_json

